### ISSUE TITLE
lastest image doesnt'work

### ISSUE THREAD

**Issue by Arryboom** [robertdebock/docker-centos-openssh#32]
with lastest image 20211212 pulled,the ssh connect is closed even when we connect by docker host got
```
[root@dockerhost tmp]# ssh root@ssh.docker.com -i key.key
Connection closed by 8.8.8.8 port 22
```

small modify to your * start.sh *
```
/usr/sbin/sshd -D
```
to 
```
/usr/sbin/sshd -D -E /var/log/sshd.log
```
 to view log output showed:

```
[root@node log]# tail -F sshd.log
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
Connection reset by 123.333.333.555 port 1206 [preauth]
linux_audit_write_entry failed: Operation not permitted
linux_audit_write_entry failed: Operation not permitted
linux_audit_write_entry failed: Operation not permitted
```

**Comment by Arryboom** [comment]
may a Centos Docker HOST specific issue:https://bugzilla.redhat.com/show_bug.cgi?id=1923728

**Comment by Arryboom** [comment]
Yes we have dropped the audit_write capability by default.  Since this is a very rare case and can easily be fixed by adding it on the command line
```
podman run --cap-add AUDIT_WRITE -p 22000:22 --expose=22 -it centos:7 /bin/bash -c "yum install -y openssh-server && ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' && /usr/sbin/sshd -Dd"```

**Comment by robertdebock** [comment]
Ah, okay. So; I don't think I can fix this in the image right?

**Comment by Arryboom** [comment]
> Ah, okay. So; I don't think I can fix this in the image right?

Thanks,as you can see it turns out this is a podman specific issue,would you like to add this tips ```--cap-add AUDIT_WRITE``` on centos to your readme.md so can help people who encounter similar problem?
